package client

import (
	"crypto/sha256"
	"crypto/subtle"
	"crypto/tls"
	"crypto/x509"
	"encoding/hex"
	"errors"
	"fmt"
	"net"
	"os"
	"strings"

	"ehang.io/nps/lib/config"
)

// TLSOptions controls how an NPC client authenticates the TLS Bridge. A CA
// file provides normal certificate-chain validation; Fingerprint pins the
// server certificate for the self-signed certificate generated by NPS.
// InsecureSkipVerify is an explicit compatibility escape hatch and should be
// used only when the connection is otherwise protected by a trusted network.
type TLSOptions struct {
	CAFile             string
	ServerName         string
	Fingerprint        string
	InsecureSkipVerify bool
}

func TLSOptionsFromConfig(commonConfig *config.CommonConfig) TLSOptions {
	if commonConfig == nil {
		return TLSOptions{}
	}
	return TLSOptions{
		CAFile:             commonConfig.TLSCAFile,
		ServerName:         commonConfig.TLSServerName,
		Fingerprint:        commonConfig.TLSFingerprint,
		InsecureSkipVerify: commonConfig.TLSInsecureSkipVerify,
	}
}

func tlsClientConfig(server string, options TLSOptions) (*tls.Config, error) {
	config := &tls.Config{MinVersion: tls.VersionTLS12}
	config.ServerName = strings.TrimSpace(options.ServerName)
	if config.ServerName == "" {
		if host, _, err := net.SplitHostPort(strings.TrimSpace(server)); err == nil {
			config.ServerName = host
		} else {
			config.ServerName = strings.TrimSpace(server)
		}
	}
	if options.CAFile != "" {
		pemBytes, err := os.ReadFile(options.CAFile)
		if err != nil {
			return nil, fmt.Errorf("read TLS CA file: %w", err)
		}
		pool := x509.NewCertPool()
		if !pool.AppendCertsFromPEM(pemBytes) {
			return nil, errors.New("TLS CA file does not contain a certificate")
		}
		config.RootCAs = pool
	}

	fingerprint, err := parseTLSFingerprint(options.Fingerprint)
	if err != nil {
		return nil, err
	}
	if len(fingerprint) > 0 {
		// A pinned certificate is an explicit trust decision. Skip the system
		// chain check, then require an exact SHA-256 match below.
		config.InsecureSkipVerify = true
		config.VerifyConnection = func(state tls.ConnectionState) error {
			if len(state.PeerCertificates) == 0 {
				return errors.New("TLS peer did not provide a certificate")
			}
			got := sha256.Sum256(state.PeerCertificates[0].Raw)
			if subtle.ConstantTimeCompare(got[:], fingerprint) != 1 {
				return errors.New("TLS server certificate fingerprint mismatch")
			}
			return nil
		}
	} else {
		config.InsecureSkipVerify = options.InsecureSkipVerify
	}
	return config, nil
}

func parseTLSFingerprint(value string) ([]byte, error) {
	value = strings.TrimSpace(strings.ToLower(value))
	if value == "" {
		return nil, nil
	}
	for _, prefix := range []string{"sha256:", "sha256/"} {
		value = strings.TrimPrefix(value, prefix)
	}
	value = strings.NewReplacer(":", "", "-", "", " ", "").Replace(value)
	if len(value) != sha256.Size*2 {
		return nil, errors.New("TLS fingerprint must be a SHA-256 hex value")
	}
	fingerprint, err := hex.DecodeString(value)
	if err != nil {
		return nil, fmt.Errorf("invalid TLS fingerprint: %w", err)
	}
	return fingerprint, nil
}
