# syntax=docker/dockerfile:1.7

FROM --platform=$BUILDPLATFORM golang:1.24 AS builder

ARG TARGETOS=linux
ARG TARGETARCH=amd64
ARG TARGETVARIANT
ARG GOPROXY=https://proxy.golang.org,direct

ENV GOPROXY=$GOPROXY
WORKDIR /src

COPY go.mod go.sum ./
RUN --mount=type=cache,target=/go/pkg/mod go mod download

COPY . .
RUN --mount=type=cache,target=/go/pkg/mod \
    --mount=type=cache,target=/root/.cache/go-build \
    set -eux; \
    goarm="${TARGETVARIANT:-}"; \
    goarm="${goarm#v}"; \
    if [ "$TARGETARCH" != "arm" ]; then goarm=""; fi; \
    CGO_ENABLED=0 GOOS="$TARGETOS" GOARCH="$TARGETARCH" GOARM="$goarm" \
        go build -trimpath -ldflags="-w -s -extldflags -static" -o /out/npc ./cmd/npc/npc.go

FROM scratch
COPY --from=builder /out/npc /npc
VOLUME ["/conf"]
ENTRYPOINT ["/npc"]
